/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerOfficerIdRouteImport } from './routes/officer.$officerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerOfficerIdRoute = OfficerOfficerIdRouteImport.update({
  id: '/officer/$officerId',
  path: '/officer/$officerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/officer/$officerId': typeof OfficerOfficerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/officer/$officerId': typeof OfficerOfficerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/officer/$officerId': typeof OfficerOfficerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/officer/$officerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/officer/$officerId'
  id: '__root__' | '/' | '/officer/$officerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficerOfficerIdRoute: typeof OfficerOfficerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/$officerId': {
      id: '/officer/$officerId'
      path: '/officer/$officerId'
      fullPath: '/officer/$officerId'
      preLoaderRoute: typeof OfficerOfficerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficerOfficerIdRoute: OfficerOfficerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
